/** Original draft for this product. Confirm the operator and obtain legal review before public release. */
export const TERMS_VERSION = "2026-09-28.1";
export const TERMS_DATE = "September 27, 2026";
export const LEGAL_OPERATOR = {
  legalName: "",
  location: "",
  contactEmail: "",
};
export const operatorDetailsComplete = Object.values(LEGAL_OPERATOR).every((value) => value.trim().length > 0);

export const RELIANCE_NOTICE = "Use this information at your own risk. We work to source information from authoritative public records, but source data, automated processing, summaries, and AI-generated interpretations can contain errors or omissions. Independently verify important facts against the official sources before relying on them.";

export interface LegalSection { id: string; title: string; paragraphs: string[] }

export const DISCLAIMER_SECTIONS: LegalSection[] = [
  { id: "reliance-and-ai", title: "Use at your own risk; errors and AI limitations", paragraphs: [
    RELIANCE_NOTICE,
    "Generative AI and automated agents can produce plausible but incorrect statements, misread a rule, miss an exception, or cite a source that does not support a conclusion. This applies to AI-assisted work and to interpretations produced by an external AI client. An authoritative citation or confident explanation does not guarantee that the result is accurate, complete, current, or appropriate for a particular situation.",
    "You are responsible for evaluating and verifying information you choose to use. To the extent permitted by applicable law, your use of and reliance on the service and its outputs are at your own risk. This notice does not waive mandatory consumer protections or exclude liability that cannot lawfully be excluded. The limitations and preserved rights in the Terms of Use apply.",
  ] },
  { id: "information-only", title: "Information and research only", paragraphs: [
    "Results reflect explicit research criteria and published area-level facts. We do not assess neighborhood desirability, compatibility with residents, suitability for any person, or where someone should buy, rent, or invest. Higher or lower values do not mean better or worse. Accounts do not personalize results according to personal characteristics.",
    "Opportunity Zone screening provides general explanations of published rules and public data about U.S. places. Its maps, comparisons, narratives, illustrations, downloadable files, and tool responses are informational only. They are not investment, financial, tax, legal, accounting, appraisal, engineering, or other professional advice.",
    "The service does not evaluate anyone's personal circumstances, recommend an investment or allocation, select a fund or transaction, or determine an individual's tax treatment. Using it does not establish an advisory, fiduciary, attorney-client, or other professional relationship with the operator, its owners, contributors, or service providers. Nothing on the service is an offer to sell or a solicitation to buy a security.",
  ] },
  { id: "verify-before-relying", title: "Verify the facts and applicable rules", paragraphs: [
    "A search match indicates that published data meets selected screening criteria. It does not certify a property's zone status or establish that a fund, business, property, transaction, or person satisfies a legal requirement. Eligibility for nomination is different from certified designation. Historical and current tract boundaries may differ.",
    "Statutes, regulations, agency guidance, designations, and source data can change. Summaries may omit exceptions or facts relevant to a particular situation. Confirm current requirements with the responsible agency and obtain advice from qualified professionals before acting on a transaction, filing, deadline, or investment decision. Official sources govern if they differ from an explanation here.",
  ] },
  { id: "data-limitations", title: "Data, geographic, and analytical limitations", paragraphs: [
    "Source records can be incomplete, delayed, revised, or incorrect. Dataset build dates are not the observation dates of every underlying measure. Missing values are not zero. Population estimates, statistical comparisons, weighted averages, and geographic crosswalks involve uncertainty; a displayed difference is not necessarily statistically significant or causal.",
    "Geocoding and mapped boundaries may be approximate. Tract and county statistics do not describe every property or person within them. Home values and rents are area estimates, not property appraisals or actual asking prices. Hazard and infrastructure layers do not replace site inspections, surveys, insurance determinations, or professional assessments. Historical patterns do not predict or guarantee future results, returns, tax benefits, or development outcomes.",
  ] },
  { id: "independence", title: "Independent service and external sources", paragraphs: [
    "The service is independently operated and is not a government agency. A government citation, agency name, link, or dataset does not imply sponsorship, approval, certification, or endorsement of this service or a location. The service uses Census Bureau API data and is not endorsed or certified by the Census Bureau.",
    "External websites, map services, data providers, and connected AI clients have their own terms and practices. Their availability and content are outside the operator's control. If an external AI client interprets a tool response, verify that interpretation against the cited sources; the client may add errors or unsupported conclusions.",
  ] },
];

export const TERMS_SECTIONS: LegalSection[] = [
  { id: "agreement", title: "1. Agreement and scope", paragraphs: [
    "These Terms of Use govern the hosted Opportunity Zone screening website, MCP server, and research features. The operator identified on this page is referred to as the operator or we. By selecting the acknowledgment and clicking “I agree and enter,” “Start with a place,” or “Accept terms and create MCP token,” or “Accept terms and replace MCP token,” you agree to these terms and acknowledge the Disclaimer and Privacy Notice. If you do not agree, do not enter or use the research features. Legal, accessibility, and connection instructions remain available without acceptance. Client permission to call a tool does not replace acceptance of this service’s terms.",
    "You must have the legal capacity to enter this agreement. If you act for an organization, you represent that you are authorized to accept these terms for it. Access is provided for lawful informational research, including commercial research, subject to applicable source licenses and these terms. Separately licensed software and data retain their own license terms.",
  ] },
  { id: "responsible-use", title: "2. Responsible use", paragraphs: [
    "Do not use this service to facilitate unlawful discrimination in housing, discriminatory steering, or unlawful exclusion or targeting of prospective buyers or renters. Lawful place research and reuse consistent with source licenses remain permitted. The service does not supply resident compatibility scores, tenant screening, housing advertising audiences, or transaction recommendations.",
    "You are responsible for your decisions and for independently checking information relevant to them. Do not present a result as an official certification, professional opinion, guaranteed outcome, or endorsement by the operator or a source agency. Keep relevant source attribution, dates, geographic scope, limitations, and disclaimers with redistributed reports.",
    "Do not disrupt the hosted service, introduce malicious code, bypass access or rate controls, infringe others' rights, or use the service unlawfully. Do not attempt to identify confidential Census survey respondents from statistical data. These hosted-service restrictions do not limit rights expressly granted by an applicable open-source or open-data license.",
  ] },
  { id: "licenses", title: "3. Software, data, and third-party rights", paragraphs: [
    "Government data, openly licensed datasets, software, and other third-party materials remain subject to their respective rights, attribution requirements, and licenses. These terms do not claim ownership of public-domain data or remove permissions under the project's MIT software license. No permission is granted to use a third party's name or mark to suggest an affiliation or endorsement that does not exist.",
  ] },
  { id: "availability", title: "4. Availability and changes", paragraphs: [
    "Public website browsing is available without an account. MCP connections require a free signed-in account and explicit acceptance of the current terms. Free passkey accounts provide additional research features and limited exports, subject to displayed allowances and shared source capacity. No payment method is requested. Keep another passkey or recovery codes; without them we cannot recover access. Account and live-data features may be unavailable while hosting is not configured. Access limits govern this hosted service and do not claim ownership of public facts or restrict separate license rights.",
    "Features, source coverage, and access may change or become unavailable. The operator may limit or suspend hosted access to address misuse, security issues, maintenance, or service constraints. There is no promise of continuous availability, preservation of a browser research session, or a particular update schedule. Keep your own copies of research you need.",
    "Revised terms will identify a new version and date. The website will request acceptance of that version before further use of its research features. Changes do not retroactively change rights or obligations concerning a dispute that arose before the revised terms took effect. You may stop using the service at any time.",
  ] },
  { id: "warranties", title: "5. Disclaimer of warranties", paragraphs: [
    "TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE AND ITS OUTPUTS ARE PROVIDED AS IS AND AS AVAILABLE. THE OPERATOR DOES NOT WARRANT THEIR ACCURACY, COMPLETENESS, TIMELINESS, AVAILABILITY, SECURITY, OR FITNESS FOR A PARTICULAR PURPOSE, AND DISCLAIMS EXPRESS, IMPLIED, AND STATUTORY WARRANTIES, INCLUDING MERCHANTABILITY AND NON-INFRINGEMENT. NO OUTPUT OR COMMUNICATION CREATES A WARRANTY THAT IS NOT EXPRESSLY REQUIRED BY LAW.",
  ] },
  { id: "liability", title: "6. Limitations of liability and rights preserved", paragraphs: [
    "To the extent applicable law permits, the operator and its owners, officers, employees, and contributors are not liable for indirect, consequential, incidental, special, exemplary, or punitive damages arising from use of, reliance on, or inability to use the service. This includes lost profits, investment opportunities, anticipated tax benefits, business interruption, and lost data, even if the possibility of such loss was communicated.",
    "These terms do not exclude or limit liability for fraud, willful misconduct, gross negligence, or any liability that applicable law prohibits excluding or limiting. Mandatory consumer protections and other nonwaivable rights remain in effect. If a limitation is not allowed in your jurisdiction, it applies only to the extent the law permits.",
  ] },
  { id: "third-party-claims", title: "7. Third-party claims arising from misuse", paragraphs: [
    "To the extent permitted by law, you agree to reimburse the operator and its owners, officers, employees, and contributors for reasonable losses and legal expenses arising from a third-party claim caused by your unlawful use of the hosted service, knowing misrepresentation of its outputs, or material violation of these terms or another party's rights. This obligation does not cover a claim to the extent caused by the protected party's fraud, willful misconduct, gross negligence, or other conduct for which the law prohibits shifting liability.",
    "The operator must provide reasonably prompt notice of a claim for which reimbursement is sought and allow reasonable participation in its defense. No settlement may impose an admission or nonmonetary obligation on you without your consent.",
  ] },
  { id: "general-terms", title: "8. General provisions", paragraphs: [
    "If a provision is unenforceable, the remaining provisions continue to apply to the extent legally permitted. A failure to enforce a provision on one occasion does not waive it on another. These terms, the Disclaimer, and the Privacy Notice describe the agreement for hosted use; they do not replace separate third-party licenses or mandatory law.",
    "Questions about these terms or factual corrections may be directed to the operator using the contact information on this page. Do not include confidential financial, tax, or legal records in a correction request.",
  ] },
];

export const PRIVACY_SECTIONS: LegalSection[] = [
  { id: "privacy", title: "Privacy notice", paragraphs: [
    "Optional browser-based MCP connection setup uses OAuth authorization codes with PKCE. By selecting Agree and connect after checking the acknowledgment, you accept these documents and authorize read-only research access. We retain client-supplied app names and registered callback URLs, hashed short-lived authorization codes, their proof-key challenges, target resource, account identifier, and acceptance version/fingerprint. Codes expire after two minutes and are single-use; only access-token hashes are retained. OAuth access expires within one hour and can be revoked from your account; a new connection requires approval again. Unused client registrations are removed after 30 days when no retained authorization record references them. Short-lived abuse event counters contain an event category, time bucket, and pseudonymous identifier, not tool arguments or research activity; they expire within two days. Concurrency records expire after 30 seconds. Usage budgets are shared across an account's connections.",
    "Public research does not require signup. Optional free passkey accounts do not request a name, email, phone, payment information, or personal financial details. We store a random account identifier, passkey public credentials, hashed session and recovery tokens, terms acceptance, and operational usage counts. Private passkey keys and biometric information remain with your device or passkey provider. These account records can be personal or pseudonymous data even without a name.",
    "Search inputs and research selections remain in browser memory while you navigate and are sent to the server when needed to perform a search or prepare an export. Selected public tract numbers, map settings, and some matched coordinates may appear in the URL fragment after the # sign. The fragment is not included in the HTTP request to this server, but it may remain in browser history or be included when you copy a link. Review links and exported files before sharing them.",
    "An address lookup sends the entered address through the app to the U.S. Census Geocoder. Site-context requests send relevant coordinates or geographic identifiers to the indicated public data services. The app does not intentionally persist or log geocode queries or tool arguments. Map tiles and external links involve requests to other providers, which may receive network information such as your IP address and are governed by their own practices.",
    "Entry requires a server-verified acceptance receipt for public visitors and account holders. We record a hash of a random receipt token, the terms version and document fingerprint, acceptance time, expiration, channel (website or MCP), and revocation status. Consent receipts are retained for up to 90 days and do not record names, IP addresses, user agents, or research activity. The accepted legal document is archived separately. Website receipts use an HttpOnly cookie valid for up to seven days; MCP tokens last up to 30 days and must be kept private. MCP acceptance records also include the account and connection identifiers. We store the connection label, creation time, a coarse last-used timestamp, and usage counts; no MCP questions or tool arguments are logged. Only token hashes are stored on the server. You can review, replace, or revoke connections from My account. Replacing a token immediately invalidates its predecessor. Anonymous MCP tokens issued before account-based connections are no longer accepted. New terms or changes to the legal document require renewed acceptance. Account sessions use a separate HttpOnly cookie with a seven-day expiration; sign-in challenges expire after five minutes. Recovery tokens are stored as hashes. Research files are prepared on the server; reopening a saved selections file reads it in your browser, then requests the selected published facts. It does not upload private models or embedded personal records.",
    "Account usage events retain operation type, time, and counts for up to 35 days. Prepared files containing public tract data and selected criteria may be retained for up to one hour for authenticated download retries. Exact searched addresses and coordinates are excluded. When a trusted hosting proxy is configured, short-lived keyed network identifiers help limit abuse; the app does not persist raw IP addresses. These identifiers rotate daily and related records expire within two days. Without that proxy configuration, a conservative shared network allowance applies. Expired records are removed during routine service use; backups and hosting logs require separate operator retention controls.",
    "You can delete your account and its credentials, sessions, recovery records, usage, prepared exports, MCP connections, and account-linked MCP acceptance records through the account panel after recent authentication. Short-lived shared network protections can remain. Accounts are used for access and allowances, not behavioral neighborhood recommendations. Public geographic source caches contain place facts, not individual search histories. When you explicitly save a workbench project, its name, notes, public tract selections, and criteria are stored in this browser’s local storage until you remove the saved copy or clear site data. Shared specifications and server exports exclude names and notes. Imported lists and release files are read in your browser; valid tract IDs may be sent for matching. A correction draft is sent to the public repository only when you choose to open its issue form, under that provider’s policies.",
    "The application does not include advertising or analytics tracking. Hosting and network providers may process ordinary request and security metadata under their own policies. This notice does not promise that all infrastructure or third-party logging is disabled. An external AI client or MCP host may store its own conversations and tool activity; consult that provider's settings and policies before entering sensitive information.",
  ] },
];
