import path from "node:path";

/** Raw downloads land here. Gitignored; regenerated by `npm run pipeline`. */
export const CACHE_DIR = path.resolve(import.meta.dirname, "cache");

/**
 * Cleaned intermediate tables: one tidy CSV per source, on the source's own
 * geography, before anything is joined. Gitignored and reproducible from the
 * cache. Splitting raw from clean means a join bug never needs a re-download.
 */
export const CLEAN_DIR = path.resolve(import.meta.dirname, "clean");

/** Committed pipeline outputs the app and the MCP server read at runtime. */
export const DATA_DIR = path.resolve(import.meta.dirname, "..", "data");

/**
 * The current ACS 5-year vintage, and a prior one far enough back that the two
 * samples do not overlap — the Census Bureau's own condition for comparing
 * 5-year estimates. 2020-2024 against 2015-2019 satisfies it.
 */
export const ACS_VINTAGE = 2024;
export const ACS_PRIOR_VINTAGE = 2019;

/** 2020 census tract boundaries, the vintage the 2027 designation round uses. */
export const BOUNDARY_VINTAGE = 2020;

/**
 * Jurisdictions that nominate tracts.
 *
 * IRC 1400Z-1(c)(3) with 7701(a)(10) makes "State" mean every state, the
 * District of Columbia, and every U.S. territory — 56 jurisdictions, each
 * nominating through its chief executive under the same 25 percent cap. So the
 * island areas are in scope for the statute even though the ACS does not cover
 * them, and the pipeline has to reach them through a second source rather than
 * dropping them.
 *
 * `source` records which one:
 *  - `acs`   the 2020-2024 ACS 5-year estimates. 50 states, DC, Puerto Rico.
 *  - `decia` the 2020 Census of Island Areas Demographic and Housing
 *            Characteristics file, which is what Treasury used for American
 *            Samoa, Guam, the Northern Marianas and the U.S. Virgin Islands.
 */
export interface State {
  fips: string;
  usps: string;
  name: string;
  source: "acs" | "decia";
}

export const STATES: readonly State[] = [
  { fips: "01", usps: "AL", name: "Alabama", source: "acs" },
  { fips: "02", usps: "AK", name: "Alaska", source: "acs" },
  { fips: "04", usps: "AZ", name: "Arizona", source: "acs" },
  { fips: "05", usps: "AR", name: "Arkansas", source: "acs" },
  { fips: "06", usps: "CA", name: "California", source: "acs" },
  { fips: "08", usps: "CO", name: "Colorado", source: "acs" },
  { fips: "09", usps: "CT", name: "Connecticut", source: "acs" },
  { fips: "10", usps: "DE", name: "Delaware", source: "acs" },
  { fips: "11", usps: "DC", name: "District of Columbia", source: "acs" },
  { fips: "12", usps: "FL", name: "Florida", source: "acs" },
  { fips: "13", usps: "GA", name: "Georgia", source: "acs" },
  { fips: "15", usps: "HI", name: "Hawaii", source: "acs" },
  { fips: "16", usps: "ID", name: "Idaho", source: "acs" },
  { fips: "17", usps: "IL", name: "Illinois", source: "acs" },
  { fips: "18", usps: "IN", name: "Indiana", source: "acs" },
  { fips: "19", usps: "IA", name: "Iowa", source: "acs" },
  { fips: "20", usps: "KS", name: "Kansas", source: "acs" },
  { fips: "21", usps: "KY", name: "Kentucky", source: "acs" },
  { fips: "22", usps: "LA", name: "Louisiana", source: "acs" },
  { fips: "23", usps: "ME", name: "Maine", source: "acs" },
  { fips: "24", usps: "MD", name: "Maryland", source: "acs" },
  { fips: "25", usps: "MA", name: "Massachusetts", source: "acs" },
  { fips: "26", usps: "MI", name: "Michigan", source: "acs" },
  { fips: "27", usps: "MN", name: "Minnesota", source: "acs" },
  { fips: "28", usps: "MS", name: "Mississippi", source: "acs" },
  { fips: "29", usps: "MO", name: "Missouri", source: "acs" },
  { fips: "30", usps: "MT", name: "Montana", source: "acs" },
  { fips: "31", usps: "NE", name: "Nebraska", source: "acs" },
  { fips: "32", usps: "NV", name: "Nevada", source: "acs" },
  { fips: "33", usps: "NH", name: "New Hampshire", source: "acs" },
  { fips: "34", usps: "NJ", name: "New Jersey", source: "acs" },
  { fips: "35", usps: "NM", name: "New Mexico", source: "acs" },
  { fips: "36", usps: "NY", name: "New York", source: "acs" },
  { fips: "37", usps: "NC", name: "North Carolina", source: "acs" },
  { fips: "38", usps: "ND", name: "North Dakota", source: "acs" },
  { fips: "39", usps: "OH", name: "Ohio", source: "acs" },
  { fips: "40", usps: "OK", name: "Oklahoma", source: "acs" },
  { fips: "41", usps: "OR", name: "Oregon", source: "acs" },
  { fips: "42", usps: "PA", name: "Pennsylvania", source: "acs" },
  { fips: "44", usps: "RI", name: "Rhode Island", source: "acs" },
  { fips: "45", usps: "SC", name: "South Carolina", source: "acs" },
  { fips: "46", usps: "SD", name: "South Dakota", source: "acs" },
  { fips: "47", usps: "TN", name: "Tennessee", source: "acs" },
  { fips: "48", usps: "TX", name: "Texas", source: "acs" },
  { fips: "49", usps: "UT", name: "Utah", source: "acs" },
  { fips: "50", usps: "VT", name: "Vermont", source: "acs" },
  { fips: "51", usps: "VA", name: "Virginia", source: "acs" },
  { fips: "53", usps: "WA", name: "Washington", source: "acs" },
  { fips: "54", usps: "WV", name: "West Virginia", source: "acs" },
  { fips: "55", usps: "WI", name: "Wisconsin", source: "acs" },
  { fips: "56", usps: "WY", name: "Wyoming", source: "acs" },
  { fips: "72", usps: "PR", name: "Puerto Rico", source: "acs" },
];

/**
 * The four island areas the ACS does not survey. They still nominate tracts
 * under the same statute, so their eligibility comes from the 2020 Census of
 * Island Areas Demographic and Housing Characteristics file instead. Keeping
 * them in a separate list makes the different provenance impossible to overlook,
 * and the manifest reports the vintage mismatch rather than implying that every
 * tract in the country was measured the same way.
 */
export const ISLAND_AREAS: readonly State[] = [
  { fips: "60", usps: "AS", name: "American Samoa", source: "decia" },
  { fips: "66", usps: "GU", name: "Guam", source: "decia" },
  { fips: "69", usps: "MP", name: "Northern Mariana Islands", source: "decia" },
  { fips: "78", usps: "VI", name: "U.S. Virgin Islands", source: "decia" },
];

/** All 56 nominating jurisdictions, whatever their data source. */
export const JURISDICTIONS: readonly State[] = [...STATES, ...ISLAND_AREAS];

export function stateByFips(fips: string): State | undefined {
  return JURISDICTIONS.find((s) => s.fips === fips);
}

/**
 * The Census API accepts at most 50 fields per `get=`, and NAME plus the
 * geography columns count against that. Batching at 24 leaves comfortable
 * headroom and keeps one state's response near 2 MB.
 */
export const VARS_PER_REQUEST = 24;

/** How many state requests to run at once. The API tolerates this; be polite. */
export const FETCH_CONCURRENCY = 6;
