"use client";
import { useState } from "react";
import Link from "next/link";
import { CoverageMap } from "./ResearchMaps";
import type { ResearchCatalog } from "@/lib/research/catalog";
import type { baseline, coverage } from "@/lib/research/catalog";
import ExportResearch from "./ExportResearch";
import { displayValue } from "@/lib/client/presentation";

export async function researchRequest<T>(body: unknown): Promise<T> { const response = await fetch("/api/research", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const value = await response.json(); if (!response.ok) throw new Error(value.error ?? "Research request unavailable."); return value; }
const valueText = (v: number | null | undefined, unit?: string) => displayValue(v, unit === "USD" ? "usd" : unit === "share" ? "pct" : "count");
export default function DataResearch({ catalog, geoids, initialGeoid = "" }: { catalog: ResearchCatalog; geoids: string[]; initialGeoid?: string }) {
  const [column, setColumn] = useState("population"); const [state, setState] = useState("");
  const [geoid, setGeoid] = useState(initialGeoid || geoids[0] || ""); const [scope, setScope] = useState<"tract" | "county" | "state" | "selection">("tract");
  const [result, setResult] = useState<{ key: string; baseline: ReturnType<typeof baseline> } | null>(null);
  const [groups, setGroups] = useState<{ key: string; groups: ReturnType<typeof coverage> } | null>(null);
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const measure = catalog.columns.find((c) => c.name === column)!; const baselineKey = JSON.stringify({ column, geoid, scope, geoids }); const coverageKey = `${column}:${state}`;
  const current = result?.key === baselineKey ? result.baseline : null;
  async function run(action: "coverage" | "baseline") { setBusy(true); setMessage(""); try { if (action === "coverage") setGroups({ key: coverageKey, ...(await researchRequest<{ groups: ReturnType<typeof coverage> }>({ action, column, ...(state ? { state } : {}) })) }); else setResult({ key: baselineKey, baseline: await researchRequest({ action, column, geoid, scope, geoids }) }); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }
  return <div className="lab-stack"><section className="lab-card"><p className="eyebrow">Definitions before calculations</p><h2>Source lineage & data dictionary</h2><label>Published measure<select value={column} onChange={(e) => setColumn(e.target.value)}>{catalog.columns.map((c) => <option key={c.name} value={c.name}>{c.label}</option>)}</select></label><ol className="lineage-steps"><li><strong>Field</strong><code>{measure.name}</code><span>{measure.description}</span></li><li><strong>Definition & units</strong><span>{measure.unit ?? "See source"}; missing values are unavailable, never zero.</span></li><li><strong>Processing & scope</strong><span>{measure.method}</span><small>{measure.geography}</small></li><li><strong>Original source</strong><a href={measure.url} target="_blank" rel="noopener noreferrer">{measure.sourceName} ↗</a><span>{measure.publisher} · {measure.vintage}</span></li></ol><p className="hint">{measure.license} · {measure.attribution}. Dataset built {catalog.version}; observation periods differ by source.</p><p className="hint">Ratios and shares use the denominator defined in the source methodology. No new denominator or uncertainty estimate is inferred here.</p><ExportResearch key={column} input={{ columns: [column], dictionaryOnly: true }} label="Download this field’s dictionary and sources" /></section>
  <section className="lab-card"><p className="eyebrow">Where information is present</p><h2>Data coverage atlas</h2><p>Coverage describes available records, not neighborhood quality. All tiles are equally sized; positions do not represent geographic boundaries.</p><div className="lab-inline"><label>Geographic detail<select value={state} onChange={(e) => setState(e.target.value)}><option value="">All states & territories</option>{catalog.states.map((s) => <option key={s.fips} value={s.fips}>{s.name} counties</option>)}</select></label><button className="button" disabled={busy} onClick={() => void run("coverage")}>Show coverage</button></div>{groups?.key === coverageKey && <><CoverageMap groups={groups.groups} state={state} /><div className="coverage-atlas" aria-label="Coverage tiles">{groups.groups.map((g) => <div className="coverage-tile" key={g.id}><strong>{g.name}</strong><meter min={0} max={g.total} value={g.available} aria-label={`${g.name} available records`} /><span>{g.available.toLocaleString("en-US")} / {g.total.toLocaleString("en-US")} available</span><small>{g.total - g.available} missing · {g.total ? (g.available / g.total * 100).toFixed(1) : "0"}% coverage</small></div>)}</div><p className="hint">Observation vintage: {measure.vintage}. Scope: {measure.geography}. A newer build date does not make source observations newer.</p></>}</section>
  <section className="lab-card"><p className="eyebrow">Choose the reference explicitly</p><h2>Geographic scale & comparison baseline</h2><div className="lab-inline"><label>Tract GEOID<input value={geoid} onChange={(e) => setGeoid(e.target.value.trim())} placeholder="11-digit tract identifier" maxLength={11} /></label><label>Reference group<select value={scope} onChange={(e) => setScope(e.target.value as typeof scope)}><option value="tract">This tract</option><option value="county">Tracts in its county</option><option value="state">Tracts in its state</option><option value="selection">My explicit tract selection</option></select></label><button className="button" disabled={busy || !/^\d{11}$/.test(geoid) || (scope === "selection" && !geoids.length)} onClick={() => void run("baseline")}>Compare published values</button></div>{current && <><h3>{current.label}</h3><dl className="lab-facts"><div><dt>Selected tract</dt><dd>{valueText(current.value, measure.unit)}</dd></div><div><dt>Median of available tract values</dt><dd>{valueText(current.median, measure.unit)}</dd></div><div><dt>Available / total tracts</dt><dd>{current.available} / {current.total}</dd></div><div><dt>Published range</dt><dd>{valueText(current.min, measure.unit)} – {valueText(current.max, measure.unit)}</dd></div></dl><p className="hint">Each tract has equal weight. This median of tract values is not the official county/state statistic, and a median of tract medians is not a household median for the whole area. Higher or lower does not mean better.</p>{current.sum != null && <p>Sum of this count across all {current.total} tracts: {valueText(current.sum, "count")}. No total is reported when a tract value is missing.</p>}{current.permits && <p>Separately published county fact: {current.permits.units.toLocaleString("en-US")} permitted housing units in {current.permits.year}. This county total is not allocated to a tract.</p>}
  <h3>Uncertainty view</h3>{current.moe != null && current.value != null ? <><p>Published estimate: {valueText(current.value, measure.unit)} ± {valueText(current.moe, measure.unit)} (source margin of error).</p><div className="uncertainty-band"><span>{valueText(current.value - current.moe, measure.unit)}</span><span aria-hidden="true">────●────</span><span>{valueText(current.value + current.moe, measure.unit)}</span></div><p className="hint">Arithmetic estimate ± margin of error, without clipping. Consult the source for confidence level and interpretation. This does not test differences between overlapping geographies or correlated estimates.</p></> : <p>The published payload has no paired margin of error for this measure. Uncertainty is unknown here; no significance or confidence claim is made. The housing-built-since-2020 count has a paired published margin of error when available.</p>}
  <h3>Research completeness</h3><ul className="completeness-list"><li>✓ Dataset version recorded: {catalog.version}</li><li>{measure.url ? "✓" : "○"} Original source linked</li><li>✓ Source vintage and geography identified</li><li>{current.missing ? "○" : "✓"} Coverage: {current.missing} missing tract values</li><li>{current.moe == null ? "○" : "✓"} Paired uncertainty {current.moe == null ? "unavailable" : "available"}</li><li>○ Certified designation and property boundaries require separate verification in the <Link href={`/tract/${geoid}`}>place report</Link></li></ul><p className="hint">This checklist describes documentation, not suitability or transaction readiness.</p></>}</section>
  {busy && <p role="status">Reading the published dataset…</p>}{message && <p role="alert">{message}</p>}</div>;
}
