"use client";
import Link from "next/link";
import { BoundaryHistoryMap } from "./ResearchMaps";
import { useState } from "react";
import { parseRelease, releaseChanges, type ReleaseFile } from "@/lib/research/workbench";
import RefreshExport from "./RefreshExport";
import { researchRequest } from "./DataResearch";

interface BoundaryResult { pairs: Array<[string, string, number, number, number]>; totals: number[]; generated: string; note: string }
export default function ResearchHistory({ initialGeoid = "" }: { initialGeoid?: string }) {
  const [files, setFiles] = useState<Array<{ data: ReleaseFile; name: string; integrity: string } | null>>([null, null]);
  const [message, setMessage] = useState(""); const [geoid, setGeoid] = useState(initialGeoid); const [vintage, setVintage] = useState<"2010" | "2020">("2020");
  const [result, setResult] = useState<{ key: string; data: BoundaryResult } | null>(null); const [busy, setBusy] = useState(false); const [page, setPage] = useState(0);
  const [kind, setKind] = useState("");
  async function load(file: File | undefined, index: number) {
    if (!file) return; setMessage(""); setFiles((current) => current.map((item, i) => i === index ? null : item));
    try { if (file.size > 10_000_000) throw new Error("Choose a JSON export smaller than 10 MB."); const data = parseRelease(await file.text());
      const digest = Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify(data.rows))))).map((v) => v.toString(16).padStart(2, "0")).join("");
      if (data.manifest.sha256OfRowsJson && digest !== data.manifest.sha256OfRowsJson) throw new Error("The file’s row checksum does not match its receipt. Re-export the original file before comparing.");
      setFiles((current) => current.map((item, i) => i === index ? { data, name: file.name, integrity: data.manifest.sha256OfRowsJson ? "Row checksum matches its receipt; this is not an authenticity signature." : "No checksum supplied; file is unverified." } : item)); setPage(0);
    } catch (error) { setMessage((error as Error).message); }
  }
  const diff = files[0] && files[1] ? releaseChanges(files[0].data, files[1].data) : null;
  const changes = diff?.changed.filter((c) => !kind || c.kind === kind) ?? [];
  const boundary = result?.key === `${geoid}:${vintage}` ? result.data : null;
  return <div className="lab-stack"><section className="lab-card"><p className="eyebrow">Version-aware research</p><h2>What changed between releases?</h2><p>Open two area-research JSON exports. Files are read only in this browser. Different selection criteria can change the rows even when the source data has not changed.</p><div className="lab-grid">{[0, 1].map((i) => <label key={i}>{i === 0 ? "Earlier export" : "Later export"}<input type="file" accept=".json,application/json" onChange={(e) => { void load(e.target.files?.[0], i); e.target.value = ""; }} />{files[i] && <small>{files[i]!.name} · dataset {files[i]!.data.manifest.datasetVersion}<br />{files[i]!.integrity}</small>}</label>)}</div>{diff && <><dl className="lab-facts"><div><dt>Row/field differences</dt><dd>{diff.changed.length}</dd></div><div><dt>Source metadata</dt><dd>{diff.sourcesChanged ? "Changed" : "Same"}</dd></div><div><dt>Definitions</dt><dd>{diff.definitionsChanged ? "Changed; review methodology" : "Same"}</dd></div><div><dt>Selection specification</dt><dd>{diff.scopeChanged ? "Different" : "Same recorded criteria"}</dd></div></dl><p className="note">A revised published value is not necessarily a real-world change. Added or absent rows do not establish boundary changes. Check the crosswalk below and review observation periods and definitions.</p><label>Difference category<select value={kind} onChange={(e) => { setKind(e.target.value); setPage(0); }}><option value="">All differences</option>{[...new Set(diff.changed.map((c) => c.kind))].map((k) => <option key={k}>{k}</option>)}</select></label><div className="table-wrap"><table className="rules"><thead><tr><th>Tract</th><th>Field</th><th>Earlier</th><th>Later</th><th>Classification</th></tr></thead><tbody>{changes.slice(page * 25, (page + 1) * 25).map((c) => <tr key={`${c.geoid}:${c.field}`}><td>{c.geoid}</td><td>{c.field}</td><td>{c.before == null ? "Unavailable / absent" : String(c.before)}</td><td>{c.after == null ? "Unavailable / absent" : String(c.after)}</td><td>{c.kind}</td></tr>)}</tbody></table></div>{!changes.length && <p>No differences in the selected category.</p>}<div className="answer-actions"><button className="button secondary" disabled={!page} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page + 1} of {Math.max(1, Math.ceil(changes.length / 25))}</span><button className="button secondary" disabled={(page + 1) * 25 >= changes.length} onClick={() => setPage(page + 1)}>Next</button></div></>}</section>
  {files[0] && <RefreshExport earlier={files[0].data} />}
  <section className="lab-card"><p className="eyebrow">2010 ↔ 2020</p><h2>Boundary time machine</h2><p>Trace the tract relationships behind historical comparisons. Population, housing, and land weights can tell different stories about the same split or merge.</p><div className="lab-inline"><label>Tract identifier<input value={geoid} maxLength={11} onChange={(e) => setGeoid(e.target.value.trim())} /></label><label>Identifier vintage<select value={vintage} onChange={(e) => setVintage(e.target.value as typeof vintage)}><option value="2020">2020 (current published identifiers)</option><option value="2010">2010</option></select></label><button className="button" disabled={busy || !/^\d{11}$/.test(geoid)} onClick={async () => { setBusy(true); setMessage(""); try { setResult({ key: `${geoid}:${vintage}`, data: await researchRequest({ action: "boundary", geoid, vintage }) }); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }}>Trace relationships</button></div>{boundary && <><BoundaryHistoryMap key={`${geoid}:${vintage}`} pairs={boundary.pairs} /><p>{boundary.pairs.length} intersecting tract relationships found. {boundary.note}</p>{!boundary.pairs.length ? <p>No crosswalk records are published for this identifier; no continuity is inferred.</p> : <div className="table-wrap"><table className="rules"><caption>Shares within the selected tract’s recorded intersections; rounded percentages may not sum to exactly 100%.</caption><thead><tr><th>2010 tract</th><th>2020 tract</th><th>Population share</th><th>Housing share</th><th>Land share</th></tr></thead><tbody>{boundary.pairs.map((p) => <tr key={`${p[0]}:${p[1]}`}><td>{p[0]}</td><td><Link href={`/tract/${p[1]}`}>{p[1]}</Link></td>{[2, 3, 4].map((i) => <td key={i}>{boundary.totals[i - 2] ? `${(Number(p[i]) / boundary.totals[i - 2] * 100).toFixed(2)}%` : "Unavailable"}<span className="boundary-bar" style={{ width: `${boundary.totals[i - 2] ? Number(p[i]) / boundary.totals[i - 2] * 100 : 0}%` }} /></td>)}</tr>)}</tbody></table></div>}<p className="hint">A relationship diagram, not an exact property-boundary overlay. Source: Census block relationship files and 2020 block population/housing counts. Crosswalk published {new Date(boundary.generated).toLocaleDateString("en-US")}.</p><a href="https://www.census.gov/geographies/reference-files/time-series/geo/relationship-files.html">Official Census relationship files ↗</a></>}</section>
  <section className="lab-card"><h2>Rules change ledger</h2><p>Review captured source versions, text differences, and the explanations that cite them. A retrieval change does not automatically mean a legal rule changed.</p><Link className="button secondary" href="/workbench/rules">Open source change ledger →</Link></section>{busy && <p role="status">Reading tract relationships…</p>}{message && <p role="alert">{message}</p>}</div>;
}
