import Link from "next/link";
import { readFileSync } from "node:fs";
import path from "node:path";
export const metadata = { title: "Rules change ledger | Opportunity Zone Research" };
type Entry = { id: string; title: string; url: string; checked: string | null; previousRef: string; previousChecked: string | null; changed: boolean; digest: string; previousText: string; currentText: string; removed: string[]; added: string[]; moreLines: boolean; rules: Array<{ id: string; title: string; quotePresent: boolean }> };
export default async function RulesLedger({ searchParams }: { searchParams: Promise<{ source?: string }> }) {
  const ledger = JSON.parse(readFileSync(path.join(process.cwd(), "data/research-legal-history.json"), "utf8")) as { built: string; entries: Entry[] };
  const { source } = await searchParams; const chosen = ledger.entries.find((e) => e.id === source) ?? ledger.entries.find((e) => e.changed) ?? ledger.entries[0];
  return <main className="page"><Link href="/workbench#history">← Research workbench</Link><p className="eyebrow">Official-source records</p><h1>Rules change ledger</h1><p className="lead">Compare the captured source text with its tracked repository version. These are detected text changes, not determinations of legal effect.</p><p className="hint">Ledger built {ledger.built}. Each document has its own retrieval date. This page does not perform a live check of official websites.</p><form className="lab-inline"><label>Source document<select name="source" defaultValue={chosen.id}>{ledger.entries.map((entry) => <option key={entry.id} value={entry.id}>{entry.changed ? "Text changed · " : ""}{entry.title}</option>)}</select></label><button className="button">Review source</button></form><section className="lab-card"><h2>{chosen.title}</h2><p>{!chosen.previousText ? "No earlier captured version is available for comparison." : chosen.changed ? "Captured content differs from the tracked version. Review associated explanations." : "No content difference detected after ignoring retrieval dates and whitespace."}</p><a href={chosen.url}>Read the official source ↗</a><p>Captured retrieval date: {chosen.checked ?? "Unavailable"} · Previous repository commit: <code>{chosen.previousRef.slice(0, 12) || "Unavailable"}</code> · Earlier retrieval: {chosen.previousChecked ?? "Unavailable"}</p><div className="lab-grid"><article><h3>Removed or replaced text</h3>{chosen.removed.length ? chosen.removed.map((line, i) => <p className="ledger-removed" key={i}>{line}</p>) : <p>None detected.</p>}</article><article><h3>Added text</h3>{chosen.added.length ? chosen.added.map((line, i) => <p className="ledger-added" key={i}>{line}</p>) : <p>None detected.</p>}</article></div>{chosen.moreLines && <p>First 25 changed lines shown on each side. Open the full captured texts below for the remainder.</p>}<div className="lab-grid"><details><summary>Full earlier captured text</summary><pre className="ledger-text">{chosen.previousText || "No earlier capture."}</pre></details><details><summary>Full current captured text</summary><pre className="ledger-text">{chosen.currentText}</pre></details></div><h3>Explanations citing this source</h3><ul>{chosen.rules.map((rule) => <li key={rule.id}><Link href={`/rules#${rule.id}`}>{rule.title}</Link> · {rule.quotePresent ? "Quoted wording is present; context still requires review." : "Quoted wording is missing — review required."}</li>)}</ul><details><summary>Content fingerprint</summary><code className="break-text">{chosen.digest}</code><p>SHA-256 of normalized captured text. This identifies the capture; it is not an agency signature.</p></details></section></main>;
}
